// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5b37IDQB52ug4Q9gt1bTq8xWsg3K1iy8',
    appId: '1:552887583862:web:229241e76267614a7dcb57',
    messagingSenderId: '552887583862',
    projectId: 'fir-auth-2305',
    authDomain: 'fir-auth-2305.firebaseapp.com',
    storageBucket: 'fir-auth-2305.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-hANbCsMBybD4WPtpQdM1v8pMORBO8VI',
    appId: '1:552887583862:android:55e1d58137ac3f947dcb57',
    messagingSenderId: '552887583862',
    projectId: 'fir-auth-2305',
    storageBucket: 'fir-auth-2305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_M6KpzXgdYz1tlGSb6jcEd6DQrTndnBE',
    appId: '1:552887583862:ios:db6613152f2fa50b7dcb57',
    messagingSenderId: '552887583862',
    projectId: 'fir-auth-2305',
    storageBucket: 'fir-auth-2305.appspot.com',
    iosClientId: '552887583862-ai9ntk0219p68c237sn5jlg61l9d9bgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );
}
